### ISSUE TITLE
speed up nft_show --show_owners

### ISSUE THREAD

**Issue by elv-todd** [eluv-io/elv-live-js#136]
elv-live performance update:

- update our implementation of the `nft_show --show_owners` so it will be "fast"
- also check `tenant_show $TENANT --check_nfts`, make sure it's ok

re: authd endpoint, `/nft/info/:addr` just shows total

so, we'll need a change there that retrieves owners from the indexer, such as a public api  `/nft/owners/:contract`

here's the format
```
tokens:
  - warns: []
    tokenId: '1'
    owner: '0x798d20f9ebBE0762752aa7A78B6B53dfC5BB99b2'
    ordinal: '0'
    tokenURI: >-
      https://demov3.net955210.contentfabric.io/s/demov3/q/hq__AzhWCFno6gMkqYA5MFbr3nTnNscYjgTQcMtVDctyXgbB5GJm7wbyejkxSmZcXd1vtnMyWKpBFm/meta/public/nft
    holdSecs: '1686718034'
    holdEnd: 2023-06-14T04:47:14.000Z
  - warns: []
    tokenId: '2'
    owner: '0x798d20f9ebBE0762752aa7A78B6B53dfC5BB99b2'
    ordinal: '1'
    tokenURI: >-
      https://demov3.net955210.contentfabric.io/s/demov3/q/hq__AzhWCFno6gMkqYA5MFbr3nTnNscYjgTQcMtVDctyXgbB5GJm7wbyejkxSmZcXd1vtnMyWKpBFm/meta/public/nft
    holdSecs: '1686718034'
    holdEnd: 2023-06-14T04:47:14.000Z
firstTokenUri: >-
  https://demov3.net955210.contentfabric.io/s/demov3/q/hq__AzhWCFno6gMkqYA5MFbr3nTnNscYjgTQcMtVDctyXgbB5GJm7wbyejkxSmZcXd1vtnMyWKpBFm/meta/public/nft
```
